package com.amitshilo.menudeldia.domain.model

data class Restaurant(
    val id: String,
    val name: String,
    val lat: Double,
    val lng: Double,
    val address: String,
    val phone: String?,
    val thumbnailUrl: String?,
    val photos: List<String>,
    val descriptionEs: String?,
    val descriptionEn: String?,
    val openingHours: List<OpeningHours>,
    val menuPrice: Double?,
    val currency: String,
    val todayHasMenu: Boolean,
    val cuisineEmoji: String? = null,
    val cuisineType: String? = null,
    val distanceMeters: Double? = null,
    val rating: Double? = null,
    val userRatingCount: Int? = null,
    val editorialSummary: String? = null,
    val aiSummary: String? = null,
    val reviews: List<Review> = emptyList(),
    val servesLunch: Boolean = false,
    val servesVegetarianFood: Boolean = false,
    val outdoorSeating: Boolean = false,
    val reservable: Boolean = false,
    val takeout: Boolean = false,
    val includesDessert: Boolean = false,
    val includesDrink: Boolean = false,
    val menuIncludes: List<String> = emptyList(),
)

data class Review(
    val authorName: String?,
    val authorPhotoUri: String?,
    val rating: Int?,
    val text: String?,
    val originalText: String?,
    val relativeTime: String?,
)
