package com.menudeldia.seed

import java.math.BigDecimal

/**
 * On-disk representation of one restaurant in `src/main/resources/seed.json`.
 * Generated by `scripts/translate-seed.main.kts`. Hebrew columns already translated to ES + EN.
 */
data class SeedRecord(
    val name: String,
    val lat: Double? = null,
    val lng: Double? = null,
    val googlePlaceId: String?,
    val phone: String?,
    val website: String?,
    val menuPrice: BigDecimal?,
    val cuisineType: String,    // matches Cuisine enum name
    val cuisineEmoji: String,
    val priceIncludesEs: List<String>,
    val priceIncludesEn: List<String>,
    val weekdayHours: Map<String, String>,
    val vegetarianOptions: Boolean = false,
    val glutenFreeOptions: Boolean = false,
    /** Optional Hebrew-source notes preserved for traceability. */
    val sourceNotesHe: String? = null,
)
